#!/bin/bash
declare service=$1

info() {
  echo "===> $*" >&2
}

if ! kubectl get svc $service &> /dev/null ;then
  info "non existing svs: $service"
  service=""
fi
if ! [[ "${service}" ]]; then
  if [[ 1 -eq $(kubectl get svc -o go-template="{{len .items}}") ]]; then
   service=$(kubectl get svc -o jsonpath='{.items[0].metadata.name}')
   info "single service: ${service}"
  else
    PS3='Choose svc: '
    select service in $(kubectl get svc -ojsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}'); do
      info "selected: ${service}"
      break
    done
  fi
fi
namspace=$(kubectl config view --minify -ojsonpath='{.contexts[0].context.namespace}')

port=$(kubectl get svc ${service} -o jsonpath='{.spec.ports[0].port}')
cat  <<EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $service
spec:
  rules:
    - http:
        host: ${service}.${namspace}.${DNS:=k8z.eu}
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ${service}
                port:
                  number: ${port}
EOF
