#!/bin/bash
declare service=$1

if ! kubectl get svc $service &> /dev/null ;then
  echo "===> non existing svs: $service"
  service=""
fi
if ! [[ "$service" ]]; then
  PS3='Choose svc: '
  select service in $(kubectl get svc -ojsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}'); do
    echo "===> selected: $service"
    break
  done
fi

port=$(kubectl get svc ${service} -o jsonpath='{.spec.ports[0].port}')
cat  <<EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $service
spec:
  rules:
    - http:
        host: $service.$NS.${DNS:=k8z.eu}
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: $service
                port:
                  number: $port
EOF
